### ISSUE TITLE
Address PMC requirements

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/genericjmsra#67]
All EE4J projects must follow the requirements described here:
https://www.eclipse.org/ee4j/news/

**Comment by keilw** [comment]
Actually like https://github.com/eclipse-ee4j/security-examples this repository neither shows up as official Java EE part, so on behalf of Oracle, could @m0mus or @bshannon please clarify how it's related to Java EE? Was it shipped with any Java EE release or not? If not I would not see it as critical and given the documentation ended in 2006 it may not have been relevant for Java EE 8 so a JEE8 branch may not properly represent this project.

**Comment by m0mus** [comment]
@keilw I am not familiar with this project. @bshannon, can you help please?

**Comment by edbratt** [comment]
GenericJMSRA is a resource adapter that can be use to connect GlassFish 
or the Java EE RI to a number of JMS providers (MQ Series, WebLogic JMS, 
maybe others). I believe that it's setup and use is described in the 
GlassFish Administration Guide.

**Comment by keilw** [comment]
Thanks, is it pre-installed with Glassfish especially V8, or is it an extension that has to be installed?

**Comment by bshannon** [comment]
I'm pretty sure it's not included in the GlassFish distribution.
It's not required for Java EE compatibility. It's mostly just an aid
to JMS vendors who want to create a resource adapter to allow
their JMS implementation to plug into Java EE application servers.

Bottom line, PMC requirements don't need to be applied here.
